[package]
name = "sctk-adwaita"
version = "0.5.1"
edition = "2021"
authors = ["Poly <marynczak.bartlomiej@gmail.com>"]
keywords = ["sctk"]
license = "MIT"
repository = "https://github.com/PolyMeilex/sctk-adwaita"
documentation = "https://docs.rs/sctk-adwaita"
description = "Adwaita-like SCTK Frame"

[dependencies]
smithay-client-toolkit = "0.16"
tiny-skia = { version = "0.7.0", features = ["std", "simd"] }
log = "0.4"

# Draw title text using crossfont `--features crossfont`
crossfont = { version = "0.5.0", features = ["force_system_fontconfig"], optional = true }
# Draw title text using ab_glyph `--features ab_glyph`
ab_glyph = { version = "0.2.16", optional = true }

[features]
default = ["ab_glyph"]

# TODO rm and use new releases
[patch.crates-io]
owned_ttf_parser = { git = "https://github.com/alexheretic/owned-ttf-parser" }
ab_glyph = { git = "https://github.com/alexheretic/ab-glyph", branch = "variations" }
